# Generated by Django 5.1.1 on 2024-09-27 13:18

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author_name", models.CharField(max_length=80)),
                ("body", models.TextField()),
                (
                    "image",
                    cloudinary.models.CloudinaryField(
                        default="placeholder", max_length=255, verbose_name="image"
                    ),
                ),
                ("posted_date", models.DateTimeField(auto_now=True)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("#FBD1A2", "Sunset"),
                            ("#7DCFB6", "Tiffany Blue"),
                            ("#C2AFF0", "Mauve"),
                            ("#E8F7EE", "Honey Dew"),
                            ("#EFCA08", "Jonquil"),
                            ("#00A6A6", "Light Sea Green"),
                            ("#FF4B3E", "Tomatoe"),
                        ],
                        default="Sunset",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["-posted_date"],
            },
        ),
    ]
